include:
  - project: divio/infra/gitlab-pipelines
    ref: master
    file: base/.gitlab-ci.yml

build:
  image: python:3.8
  stage: build
  before_script:
    - pip install --upgrade -r requirements.txt
  script:
    - sphinx-build -b html . public
