version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: 
          name: install requirements
          command: |
            sudo apt-get update
            sudo apt-get install enchant
      - run:
          name: Sphinx test
          command: |
            make install
            make test

